name: Matsuri HR Uptime Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  check-uptime:
    runs-on: ubuntu-latest
    environment: monitoring_environment

    steps:
      - name: Check if site is up
        id: check
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://matsuri-hr.com/login)
          echo "HTTP status: $STATUS"
          echo "status_code=$STATUS" >> $GITHUB_OUTPUT

      - name: Send Slack alert if down
        if: steps.check.outputs.status_code != '200'
        env:
          SLACK_WEBHOOK: ${{ secrets.DIALOG_MONITOR_SLACK_WEBHOOK }}
        run: |
          curl -X POST "$SLACK_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "text": "🚨 *Matsuri HR Login Page is DOWN!* Status code: '${{ steps.check.outputs.status_code }}'"
            }'

      - name: Send Slack message if up
        if: steps.check.outputs.status_code == '200'
        env:
          SLACK_WEBHOOK: ${{ secrets.DIALOG_MONITOR_SLACK_WEBHOOK }}
        run: |
          curl -X POST "$SLACK_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "text": "✅ Matsuri HR Login Page is UP — everything is ok!"
            }'
