  name: Matsuri HR Jobs Page Uptime Monitor

  on:
    schedule:
      - cron: "*/5 * * * *"  # every 5 minutes -- varies by GitHub network

  jobs:
    check-uptime:
      runs-on: ubuntu-latest
      environment: monitoring_environment

      steps:
        - name: Check Jobs page status
          id: check
          run: |
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://matsuri-hr.com/jobs)
            echo "HTTP status: $STATUS"
            echo "status_code=$STATUS" >> $GITHUB_OUTPUT

        - name: Send Slack alert if down
          if: steps.check.outputs.status_code != '200'
          env:
            SLACK_WEBHOOK: ${{ secrets.DIALOG_MONITOR_SLACK_WEBHOOK }}
          run: |
            curl -X POST "$SLACK_WEBHOOK" \
              -H "Content-Type: application/json" \
              -d '{
                "text": "🚨 *Matsuri HR Jobs Page is DOWN!* Status code: '${{ steps.check.outputs.status_code }}'"
              }'

        - name: Send Slack message if up
          if: steps.check.outputs.status_code == '200'
          env:
            SLACK_WEBHOOK: ${{ secrets.DIALOG_MONITOR_SLACK_WEBHOOK }}
          run: |
            curl -X POST "$SLACK_WEBHOOK" \
              -H "Content-Type: application/json" \
              -d '{
                "text": "✅ Matsuri HR Jobs Page is UP — everything is OK!"
              }'
